version: 0.20.{build}
image:
- Visual Studio 2022

build:
  verbosity: minimal

branches:
  except:
  - gh-pages

init:
- git config --global core.autocrlf input

install:
- git submodule update --init --recursive --remote
- ps: ./tools/install.ps1

build_script:
- ps: dotnet build -c Release
- ps: pushd ref/bolero; git checkout master; git pull; .\build.cmd -t build; popd
- ps: ./tools/gen-refdoc.ps1 -BoleroSlnFolder ref/bolero

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

for:
- branches:
    only:
    - master
  on_success:
  - ps: .\tools\gh-pages.ps1 -env appveyor
